### PR TITLE
 Include patch to fix the dbus name of mediakeys so that they work 

### LINKED ISSUE #6: Media keys don't work
I see the following warning on startup
```
(rhythmbox:2): Rhythmbox-WARNING **: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

Rhythmbox integrated with the MPRIS interface and this works correct, but the media keys fail to work so one can not pause/resume next/previous with keyboard media keys :-/

There is an entry in the finish-args that claims to be for the media-keys
```
/* media keys */
"--talk-name=org.gnome.SettingsDaemon.MediaKeys",
```

### PR DESCRIPTION
**Pull request by ahayzen**
https://github.com/GNOME/rhythmbox/commit/a48c08641c2fb282fad21ff8b0f3e47932f0a656

Closes #6

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by ahayzen** [comment]
I believe I have resolved the merge conflict in this one :-)

**Comment by barthalion** [comment]
Merged your changes manually as GitHub isn't too clever about handling conflicts. Thanks again!

**Comment by ahayzen** [comment]
@Barthalion Thanks! :-)

**Pull request closed without merging**
